[pytest]
addopts = -v -s --alluredir=allure-results --html=reports/report.html --self-contained-html
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke
    regression